services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: library_sql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrong!Passw0rd -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  web:
    build: .
    container_name: library_app
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__Default=Server=db;Database=LibraryDb;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True
      - App__MaxBooks=100
    depends_on:
      db:
        condition: service_healthy

volumes:
  sqldata:
